/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BannerComponent: typeof import('./src/components/BannerComponent.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ErrorComponent: typeof import('./src/components/ErrorComponent.vue')['default']
    FooterList: typeof import('./src/components/FooterList.vue')['default']
    HotelInfo: typeof import('./src/components/HotelInfo.vue')['default']
    LoaderComponent: typeof import('./src/components/LoaderComponent.vue')['default']
    MarketBlock: typeof import('./src/components/UI/MarketBlock.vue')['default']
    NewsLetter: typeof import('./src/components/NewsLetter.vue')['default']
    OrderButton: typeof import('./src/components/UI/OrderButton.vue')['default']
    OrderForm: typeof import('./src/components/OrderForm.vue')['default']
    OrderHotel: typeof import('./src/components/OrderHotel.vue')['default']
    OrderInput: typeof import('./src/components/UI/OrderInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
    SvgIcon: typeof import('./src/components/UI/SvgIcon.vue')['default']
  }
}
