/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BannerComponent: typeof import('./src/components/BannerComponent/BannerComponent.vue')['default']
    DetailsAmenities: typeof import('./src/components/DetailsComponents/DetailsAmenities.vue')['default']
    DetailsDescription: typeof import('./src/components/DetailsComponents/DetailsDescription.vue')['default']
    DetailsExpandButton: typeof import('./src/components/UI/DetailsExpandButton.vue')['default']
    DetailsHeading: typeof import('./src/components/DetailsComponents/DetailsHeading.vue')['default']
    DetailsMap: typeof import('./src/components/DetailsComponents/DetailsMap.vue')['default']
    DetailsPage: typeof import('./src/components/DetailsPage.vue')['default']
    DetailsRating: typeof import('./src/components/DetailsComponents/DetailsReviews/DetailsRating/DetailsRating.vue')['default']
    DetailsReview: typeof import('./src/components/DetailsComponents/DetailsReviews/DetailsReview/DetailsReview.vue')['default']
    DetailsReviews: typeof import('./src/components/DetailsComponents/DetailsReviews/DetailsReviews.vue')['default']
    ErrorComponent: typeof import('./src/components/ErrorComponent/ErrorComponent.vue')['default']
    FeaturedSection: typeof import('./src/components/HomeFeaturedSection/FeaturedSection.vue')['default']
    FlatsInfo: typeof import('./src/components/DetailsComponents/FlatsInfo.vue')['default']
    GalleryLoader: typeof import('./src/components/Gallery/GalleryLoader.vue')['default']
    HostInfo: typeof import('./src/components/HotelCard/HostInfo.vue')['default']
    HotelCardItem: typeof import('./src/components/HotelCard/HotelCardItem.vue')['default']
    HotelCardList: typeof import('./src/components/HotelCard/HotelCardList.vue')['default']
    HotelInfo: typeof import('./src/components/HotelCard/HotelInfo.vue')['default']
    HotelOrder: typeof import('./src/components/DetailsComponents/HotelOrder.vue')['default']
    ImagesGallery: typeof import('./src/components/Gallery/ImagesGallery.vue')['default']
    LatestSection: typeof import('./src/components/HomeLatestSection/LatestSection.vue')['default']
    LoaderComponent: typeof import('./src/components/LoaderComponent/LoaderComponent.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent/MapComponent.vue')['default']
    MarketBlock: typeof import('./src/components/UI/MarketBlock.vue')['default']
    ModalWindow: typeof import('./src/components/UI/ModalWindow.vue')['default']
    OrderButton: typeof import('./src/components/UI/OrderButton.vue')['default']
    OrderForm: typeof import('./src/components/OrderComponents/OrderForm.vue')['default']
    OrderHotel: typeof import('./src/components/OrderComponents/OrderHotel.vue')['default']
    OrderInput: typeof import('./src/components/UI/OrderInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAboutHotel: typeof import('./src/components/SearchPageComponents/SearchAboutHotel.vue')['default']
    SearchComponent: typeof import('./src/components/SearchSection/SearchComponent.vue')['default']
    SearchHotelsList: typeof import('./src/components/SearchPageComponents/SearchHotelsList.vue')['default']
    SearchMap: typeof import('./src/components/SearchPageComponents/SearchMap.vue')['default']
    SearchSection: typeof import('./src/components/SearchSection/SearchSection.vue')['default']
    SvgIcon: typeof import('./src/components/UI/SvgIcon.vue')['default']
  }
}
