/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BannerComponent: typeof import('./src/components/BannerComponent.vue')['default']
    DetailsExpandButton: typeof import('./src/components/UI/DetailsExpandButton.vue')['default']
    ErrorComponent: typeof import('./src/components/ErrorComponent.vue')['default']
    GalleryLoader: typeof import('./src/components/GalleryLoader.vue')['default']
    HostInfo: typeof import('./src/components/HostInfo.vue')['default']
    HotelCardItem: typeof import('./src/components/HotelCardItem.vue')['default']
    HotelCardList: typeof import('./src/components/HotelCardList.vue')['default']
    HotelInfo: typeof import('./src/components/HotelInfo.vue')['default']
    ImagesGallery: typeof import('./src/components/ImagesGallery.vue')['default']
    LoaderComponent: typeof import('./src/components/LoaderComponent.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    MarketBlock: typeof import('./src/components/UI/MarketBlock.vue')['default']
    ModalWindow: typeof import('./src/components/UI/ModalWindow.vue')['default']
    OrderButton: typeof import('./src/components/UI/OrderButton.vue')['default']
    OrderInput: typeof import('./src/components/UI/OrderInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/UI/SvgIcon.vue')['default']
  }
}
